### ISSUE TITLE
Remove References to Instamobile From iOS

### ISSUE THREAD

**Issue by CollierA13j** [uah-cpe-sd-2020/myportion_app#17]
There are a couple of lines in the ios files that still reference Instamobile which was removed from the android files
https://github.com/uah-cpe-sd-2020/myportion_app/blob/22ee32a566cdc48c058722b09bbaf1ef4eef1862/ios/Runner.xcodeproj/project.pbxproj#L457

**Comment by wsciaroni** [comment]
All references are removed _enough_ for our purposes.
