### ISSUE TITLE
Create Tests for Widgets in services/helper.dart

### ISSUE THREAD

**Issue by GuassianFlux** [uah-cpe-sd-2020/myportion_app#18]
# Acceptance Criteria
* A test exists for each widget

**Comment by GuassianFlux** [comment]
Widget test pumps widget, but fails due to a lack of an http client servicing requests. A mock http client will need to be implemented to allow for a successful test.

**Comment by GuassianFlux** [comment]
## Progress Dialog Tests 
- Verifies that dialog builds with correct text
- Verifies that the dialog exists only within context
- Verifies the dialog updates text appropriately
- Verifies that hiding dialog removes it from view
## Alert Dialog Tests 
- Verifies that dialog is built with the correct text
- Verifies that the dialog exists only within context
## Push UI Tests
- Currently experiencing a type error when trying to use push()
- Test is commented and committed for inspection by others
## Display Image Tests
- I believe I found a work around for the http client mock
- Trying to find by image type returns two entities and the test fails. This might not be a problem with the test.
- test is commented and committed for inspection by others

**Comment by wsciaroni** [comment]
@GuassianFlux I made the changes to update your two failing tests. I believe all is good now.  Feel free to Open a PR for discussion on the particular code.

**Comment by wsciaroni** [comment]
@GuassianFlux I now realize that you've already fixed these and merged your changes in. I will close this issue.
