### ISSUE TITLE
Come up with topics for class lectures

### ISSUE THREAD

**Issue by CollierA13j** [uah-cpe-sd-2020/myportion_app#22]
Dr. Wells would like to know what topics we would like to know more about that could be talked about during class lectures that would help us develop this project

**Due:** Tuesday, February 9 @ 4:30pm

**Comment by wsciaroni** [comment]
We could definitely discuss Flutter/Dart and the benefits compared to developing native apps for each platform

**Comment by CollierA13j** [comment]
I think a lecture on IoT would be nice as well

**Comment by GuassianFlux** [comment]
I like the IoT device. It is general enough that we could go a lot different directions with it, and our project could be a small demonstration of one of the many IoT applications.

**Comment by wsciaroni** [comment]
Sounds reasonable to me!

**Comment by wsciaroni** [comment]
Anyone opposed to marking this as done since we've decided on a topic?

## Topic

`IoT`
