### ISSUE TITLE
Feeder list

### ISSUE THREAD

**Issue by wsciaroni** [uah-cpe-sd-2020/myportion_app#26]
I want to have a view 
- accessible from the Drawer (side bar)
- Has a list of **Feeders**
- Shows an image of the feeder type (stock photo)
- Have a `+` button to add a Feeder

**Comment by GuassianFlux** [comment]
@wsciaroni What did you envision with showing the pet's image here? Was this a typo or did you want a collage of the pet's currently on a feeder?

**Comment by wsciaroni** [comment]
@GuassianFlux  Definitely a typo... although we could do an image that was stacked like when you view a group text through Material UI.  Or... we could do without. Up to the developer I'd say.
