### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by wsciaroni** [uah-cpe-sd-2020/myportion_app#28]
We should do a `git mv` for the `Readme.md` to `StartDeveloping.md`

We should then update the `Readme.md` to describe the purpose of the app.  This way, someone who lands on our Repo will better understand what it's all about, and why they should give it a look.  It will help us look more organized.

**Comment by wsciaroni** [comment]
What's the status on this?

**Comment by wsciaroni** [comment]
Any news on this? it appears to have been sitting for 24 days

**Comment by jlp0063** [comment]
This is lowest priority as it does not directly affect the builds or completion of the Pet Feeder. Therefore, it has dropped on my priority list. When I find time, I will update, but this is not a pressing issue.
