### ISSUE TITLE
Add A Pet Process Visual Re-Work

### ISSUE THREAD

**Issue by wsciaroni** [uah-cpe-sd-2020/myportion_app#37]
## UI Changes

I would also like to see a couple of changes to the form before we get this merged in.

![Screenshot from 2021-02-26 16-27-11](https://user-images.githubusercontent.com/26583386/109362364-7b859180-7850-11eb-9e35-7d2c32552c5b.png)

On the page above I would like to see the following changes:

- [ ] Space after each time in the list.  In the image that would look like some spacing after the `7:15AM` item.
- [ ] Have the plus button at the bottom right of the **List**.  By this I mean that the `plus` button should be located above and to the right of the `Submit Feeding time` button.
- [ ] Have a way to remove an item from the list if it is not wanted anymore or too many were added by accident. Maybe using a [PopupMenuButton](https://api.flutter.dev/flutter/material/PopupMenuButton-class.html) on each item.  Or, have a way to swipe the item away.
- [ ] Have the `Submit Feeding Time` button match the formatting of the rest of our buttons.

## Main Takeaway

I would really prefer to see the list of `Feeding Times` be implemented using [ListTiles](https://api.flutter.dev/flutter/material/ListTile-class.html)

I would think that this should allow for swiping away unwanted items in the list as well as fixing the spacing issue.  Then changing the `plus` button to a [FloatingActionButton](https://api.flutter.dev/flutter/material/FloatingActionButton-class.html) should really wrap this up.

_Originally posted by @wsciaroni in https://github.com/uah-cpe-sd-2020/myportion_app/issues/36#issuecomment-786934748_

**Comment by jlp0063** [comment]
I'd like to see a finished product that does our basic functionality before making the UI feel good. This can be something we do once we have the app and the hardware communicating properly. As of now, our design needs to look good and we have to be able to use it(which we meet those needs). We can make it more user friendly later if we have time so that we can try to make this a fully marketed product.

**Comment by wsciaroni** [comment]
While the look and feel is absolutely secondary to functionality, we MUST use the correct building blocks and the look and feel will handle itself.  We need to stop reinventing the wheel. If we use the ListTiles,  FloatingActionButton, and other pre-built UI objects, we will end up with a much more cohesive product.

To summarize, we need to do things right the first time. This will simplify the programming and make a more cohesive user experience.

**Comment by wsciaroni** [comment]
If we have time later, we can always re-open this issue
