### ISSUE TITLE
Add Documentation w/ Automation

### ISSUE THREAD

**Issue by wsciaroni** [uah-cpe-sd-2020/myportion_app#4]
We should make use of some tool to document our code.  I am a huge fan of Doxygen, but it appears there may be one more purpose built for flutter apps.
I propose **dartdoc** to document our code.

Guide to documenting with DartDoc are below:
https://dart.dev/guides/language/effective-dart/documentation

Acceptance Criteria:
DartDoc should be configured to run as a GitHub action and automatically hosted on GitHub Pages.
Team Members should be brought up to date with how to document using dartdoc.

**Comment by GuassianFlux** [comment]
Blocked by #2
