### ISSUE TITLE
Create User Account

### ISSUE THREAD

**Issue by wsciaroni** [uah-cpe-sd-2020/myportion_app#5]
## Functionality

User should be able to create a user account.

- Username - Always an email.
- Password

## Acceptance Criteria:
Create an account on Firebase Authentication page.

**Comment by wsciaroni** [comment]
What's the status on this issue?

**Comment by jalobrano** [comment]
> What's the status on this issue?

I believe that this is covered by the widget tests completed in "helper widget tests" pull request.

**Comment by wsciaroni** [comment]
Excellent! Let's get this issue closed
