### ISSUE TITLE
Add Home Screen Functionality

### ISSUE THREAD

**Issue by jalobrano** [uah-cpe-sd-2020/myportion_app#50]
- Feeder Drop Down (steal from AddPetProfileScreen.dart)
- List of Pets for that particular feeder in ListTiles (check out PetListScreen.dart)
- Next Up...Section to display next up feeding times for a particular pet
- For layout, look at rough draft within #general chat on Discord

**Comment by CollierA13j** [comment]
Closed by pull request #54
