### ISSUE TITLE
Validate Email and Password input

### ISSUE THREAD

**Issue by wsciaroni** [uah-cpe-sd-2020/myportion_app#8]
## Functionality & Acceptance Criteria

The email should be validated to have the correct *form* of an email.. `___@___.___` If it Does Not have this form, the user should not be able to attempt to click 'login' or 'register'.

The password should have a minimum of 10 characters.  If it Does Not have this form, the user should not be able to attempt to click 'login' or 'register'.

The password should use an `incognito` style keyboard if available.  This would stop auto-correction or analytics from analyzing the password input.

The password should be hidden from the user, with the option to peek the input.

**Comment by wsciaroni** [comment]
What's the status on this issue?

**Comment by CollierA13j** [comment]
Deemed unnecessary for our project
