### ISSUE TITLE
Verify that Password is handled appropriately

### ISSUE THREAD

**Issue by wsciaroni** [uah-cpe-sd-2020/myportion_app#9]
A user WHO DID NOT WRITE the #8 #7 #6 #5 code should independently verify that we are in no way compromising the security of the user's password.

**Comment by wsciaroni** [comment]
This is a security audit to be sure we aren't doing anything dicey with the passwords.

We may want to have two people review this.

**Comment by GuassianFlux** [comment]
Walk through the data flow for the password.

If handled improperly, a possible solution may be to immediately overwrite the memory location of the password after it is used.

**Comment by GuassianFlux** [comment]
I reviewed the password procedure, and it looks safe to me. The firebase authentication class hashes the password, so it is only in the clear when performing validation operations. I'm good to consider this done.

**Comment by wsciaroni** [comment]
@GuassianFlux Very good. We will mark this as done.
